### ISSUE TITLE
Develop agenda

### ISSUE THREAD

**Issue by dennis-tra** [ag-gipp/decentralized-open-science#6]
Round robin:
- send invitation
- moderate
- create meeting

**Comment by dennis-tra** [comment]
Draft agenda:
1. Development of agenda
2. Stand-up
3. Fabian (5min)
4. Literature Review (20min)
5. Project Marco (20min)
6. All things considered?
7. Goodby

**Comment by physikerwelt** [comment]
Draft agenda:

1. Stand-up (15min)
2. Optimistic Provide (10min)
3. Fabian (10min)
4. Literature Review (5min)
5. Project Marco (5min)
6. Student projects for DOS
7. All things considered?
8. Goodby
